### ISSUE TITLE
scripts/Makefile.lib:193: recipe for target 'scripts/kconfig/zconf.lex.c' failed

### ISSUE THREAD

**Issue by afgcons** [AlexHowansky/lci_ldx9000_driver#1]
Firstly, a  big "THANK YOU, Alex!" for publishing your cleanup work. 

Here a much smaller contribution:  I was able to get a clean compile (Ubuntu 18.04 LTS kernel 5.0.0-36-generic) after "apt-get install build-essential bison flex" thanks to this post [here](https://www.linuxquestions.org/questions/debian-26/compile-of-kernel-4-16-fails-4175628085/).
HTH
Andreas 

attach: console messages before installing pre-req's
[t.txt](https://github.com/AlexHowansky/lci_ldx9000_driver/files/4073031/t.txt)

**Comment by AlexHowansky** [comment]
Andreas,

I will update the README to indicate that these packages may be required.

Thanks,
Alex
